package ba.unsa.si.docflow.entity.enums;

public enum AuditAction {
    DOCUMENT_ASSIGNED,
    TASK_STARTED,
    TASK_COMPLETED,
    TASK_CANCELLED,

    FIELD_ADDED,
    FIELD_UPDATED,

    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_RETURNED_FOR_CORRECTION,

    NOTIFICATION_CREATED,
    NOTIFICATION_READ,
    NOTIFICATIONS_READ_ALL,

    EMAIL_REMINDER_SENT,

    PERMISSION_DENIED,
    SYSTEM_ACTION
}
