package ba.unsa.si.docflow.entity.enums;

public enum StatusHistoryAction {
    DOCUMENT_UPLOADED,
    DOCUMENT_CREATED,
    DOCUMENT_TYPE_CONFIRMED,

    EXTRACTION_STARTED,
    EXTRACTION_COMPLETED,
    EXTRACTION_FAILED,
    EXTRACTION_RETRIED,
    EXTRACTION_CONFIRMED,
    EXTRACTION_RECONFIRMED,

    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,
    DOCUMENT_RETURNED_FOR_CORRECTION,

    DOCUMENT_REASSIGNED,
    SYSTEM_STATUS_CHANGE
}
